# Generated by Django 3.0.6 on 2020-05-10 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_item', models.CharField(choices=[('income', 'Текущие доходы'), ('expenses', 'Текущие расходы'), ('wish_list', 'Лист желаний')], default='income', max_length=9, verbose_name='Статья бюджета')),
                ('money', models.FloatField(verbose_name='Размер')),
                ('item_description', models.CharField(max_length=200, verbose_name='Описание')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
